### ISSUE TITLE
Why node 5?

### ISSUE THREAD

**Issue by bingomanatee** [weblancaster/node-react-stack-kit#4]
It seems like node 4 is just settling in; why are you setting the line at 5? What 5 features did you need that weren't in 4?

**Comment by weblancaster** [comment]
Hey @bingomanatee Node 4 is stable and the project will work on that version as well.. but I want to push to use the latest as they have security and bug fixes.

You can take a look here if you want to know in more detail https://nodejs.org/en/blog/release/v0.12.5/
