### ISSUE TITLE
i don't know why i can't run...

### ISSUE THREAD

**Issue by showzyl** [weblancaster/node-react-stack-kit#8]
showzyl@bogon:~/Downloads/node-react-stack-kit-master$ npm start

> node-react-stack-kit@1.0.0 start /Users/showzyl/Downloads/node-react-stack-kit-master
> node ./bin/www

/Users/showzyl/Downloads/node-react-stack-kit-master/bin/www:7
import app from '../app';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! node-react-stack-kit@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-react-stack-kit@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the node-react-stack-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-react-stack-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by jaychsu** [comment]
For your problem:
REF: [ECMAScript 6 modules in Node.JS](http://stackoverflow.com/questions/17330078/ecmascript-6-modules-in-node-js)

But we can run `node ./index.js` to start this project for now.

**Comment by weblancaster** [comment]
@showzyl you will need to have babel installed.. try installing globally and make sure you also have `babel-register` under your `node_modules` folder

**Comment by weblancaster** [comment]
closing this issue since no further feedback was given.
